////

|metadata|
{
    "name": "known-issues",
    "controlName": [],
    "tags": [],
    "guid": "{5E1E930D-B24D-46C1-A617-0DAF6009359F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 既知の問題

*RFT バージョン 8.1.1.3 以降で VB.NET サンプル スクリプトを再生する場合の既知の問題*

RFT バージョン 8.1.1.3 以降では、Windows Forms Test Automation (IBM) と一緒にインストールされたサンプル スクリプトを再生できません。これは、サンプル スクリプトの構築が RFT の新しいバージョンに対応していないためです。RFT 8.1.1.3 では、オブジェクト認識のフォーマットが変更されていますが、サンプル スクリプトを以前のバージョンで再生できるように、サンプル スクリプト自体は変更されていません。以下のステップを実行すると、この制限を回避できます。

[start=1]
. 失敗したスクリプトのオブジェクト マップを開きます。
[start=2]
. RFT が認識できないテスト オブジェクトを選択します。
[start=3]
. テスト オブジェクトを右クリックし、コンテキスト メニューから「強調表示」を選択します。オブジェクトを認識できなかったことが通知されます。
[start=4]
. テスト オブジェクトを再度右クリックし、「Update Recognition Properties」を選択し、画面の指示に従います。
[start=5]
. オブジェクト マップを保存すると、問題なくスクリプトを再生できるようになります。

*RFT バージョン 8.1.1.1 で VB.NET スクリプトを再生する場合の既知の問題*

RFT バージョン 8.1.1.1 で VB.NET スクリプトを再生すると、System.IO.FileNotFoundException がスローされます。IBM は、この問題を修正するパッチをまもなくリリースします。

*注:* これは VB.NET スクリプトのみの問題です。Java スクリプトは問題なく動作します。

*インストーラーの既知の問題と制限*

インストーラーを使用して {ProductName} (Rational Functional Tester) を WinServer 2003 にインストールする場合、デバッグの実行についてのエラーがスローされます。エラーに対して「いいえ」をクリックしてください。{ProductName} (Rational Functional Tester) のインストールが正常に続行されます。

*スタイル変更されたランタイム ダイアログの既知の問題*

ランタイム ダイアログのスタイルの変更により、以前のバージョン (10.1以前) の以下のダイアログに記録されたスクリプトは、再度記録する必要があります。

* WinGrid

** 概要
** CustomFilter

* ツールバー

** ユーザー設定
** ユーザー設定のキーボード
** 新規ツールバー
** コマンドの再配置
** コマンドの追加

* PrintPreviewDialog

** プレビューの生成

*WinGanttView の既知の問題*

期間を含むデータ確認ポイントを使用して 10.1 に対して以前に記録されたスクリプトは、10.2 で再度記録する必要があります。

*WinGrid の既知の問題と制限*

====== 条件付き書式ダイアログ

新しい条件付き書式ダイアログの操作を記録する場合、フォーミュラ ビルダー ダイアログの操作がスクリプトに含まれていると競合が発生します。これは既知の問題です。RFT は、フォーミュラ ビルダー ダイアログと追加条件/外観マッピング ダイアログの [OK] ボタンを 1 つのオブジェクトとみなし、記録終了時にエラーをスローします。以下のステップを実行すると、この制限を回避できます。

[start=1]
. [OK] ボタンの最初の操作で記録を停止します。
[start=2]
. オブジェクト マップの「OKButton」テスト オブジェクトを有効な別の名前に変更します。
[start=3]
. 記録を続行すると、次の [OK] ボタンは別のテスト オブジェクト名「OKButton」を取ります。

*WinListView の既知の問題と制限*

ListItem の編集で、項目をダブルクリックして編集モードにした場合のテキストの編集には、以下のいずれかを実行する必要があります。

* ダブル クリック操作の後、テキストが変更される前に、「sleep(1)」をハードコードします。
* 内部エディターでテキストを編集するには、データプールを埋め込みエディターに追加します。

*WinPanel の既知の問題と制限*

WinPanel 内で、完全に表示されていないコントロールの領域でクリック操作を再生すると、再生例外がスローされます。この例外を回避するには、クリックするコントロールの領域をビューにスクロールする操作をスクリプトに含めます。たとえば、グリッドの最初のセルが WinPanel のスクロール領域の外にある場合、セルをビュー内にスクロールする適切なボタンを予めクリックしない限り、対象のセルでのクリック操作が再生されません。

*WinSchedule の既知の問題と制限*

宛先へのパスがコントロールをスクロールをスクロールする場合の予定のドラッグでは、Drag アクションを MoveAppointment アクションに置き換える必要があります。これは、ドラッグ操作のグラス再生をさせないコントロール動作のために必要です。

*WinTilePanel の既知の問題と制限*

* タイルをある位置から別の位置にドラッグすると、タイル上のマウス ポインターの動きに合わせて、UltraTilePanel はタイルの位置を変更します。Rational Functional Tester フレームワークがドラッグ中のマウスの動きをサポートしていないため、これらの変更は記録されません。したがって、移動されたタイルは再生で同じ位置にならず、ドラッグされたタイルは記録時と同じ位置に移動するだけです。タイルの中間移動はすべて同じになりません。

*WinTimeLineView の既知の問題と制限*

* ビューに予定サブ項目または時間帯サブ項目を移動させる場合、移動したサブ項目はコントロールの左端に置かれます。
* *ドラッグ中のスクロール:* ソースとターゲットが 1 画面に表示できない場合、タイムライン プロキシによるドラッグ操作は正しく再生されません。これは、一部の Infragistics コントロールの制限とRational Functional Tester フレームワークが原因です。この制限を回避するには、以下の例を参考にしてください。1 画面に表示された時間範囲を超えた選択が必要なテストの場合は、マウス ポインターをソースからターゲットにドラッグしないでください。代わりに最初の時間帯をクリックし、マウスホイールを使用してスクロールして範囲の最後の時間帯を表示させ、シフト キーを押しながらクリックします。
* オーナー ヘッダーの端をドラッグしてビュー内のオーナー数を変更すると、正しく再生されません。同様の操作をするには、ドラッグ操作を以下のステートメントに置き換えます。

----
'ビューのオーナー数を 3 に設定する
UltraTimelineView1Calendar().SetNAProperty("MaximumOwnersInView", 3)
'ビューのオーナー数を 2 に設定する
UltraTimelineView1Calendar().SetNAProperty("MaximumOwnersInView", 2)
----

* 複数の時間帯をドラックで選択する操作では、場合によって選択が正しく再生されません。この場合は、「クリックし、次にシフト キーを押しながらクリック」を使用して、時間帯の範囲を選択します。

----
'時間帯の開始をクリック
UltraTimelineView1Calendar().Click(AtList(AtLocation("TimeSlot"), AtDate(10, 20, 2009), _
AtText("Time:00:15:00"), AtText("Owner2")))
'時間帯の終了でシフト キーを押しながらクリックし、範囲を選択
UltraTimelineView1Calendar().Click(SHIFT_LEFT, AtList(AtLocation("TimeSlot"), AtDate(10, 20, 2009), _ 
AtText("Time:02:30:00"),AtText("Owner2")))
----

* タイムライン ビューの予定をCTRL キー + ドラッグの方法でコピーすると正しく記録されますが、再生後の予定はコピーではなく移動になります。