////

|metadata|
{
    "name": "rft-whats-new-in-2011-volume-2",
    "controlName": [],
    "tags": [],
    "guid": "6809f186-e1ae-4635-8a47-8ec3b4d1ca7c",  
    "buildFlags": [],
    "createdOn": "2011-11-16T20:26:49.740027Z"
}
|metadata|
////

= 2011 Volume 2 の新機能

*WinGrid - スタイル変更条件付き書式ダイアログのオートメーション テストのサポート*

{ProductName} (Rational Functional Tester) 2011.2 リリースでは、WinGrid コントロールのスタイル変更条件付き書式ダイアログ機能に対するオートメーション テストがサポートされています。

条件付き書式ダイアログのスタイルが変更され、ユーザーはより直感的にユーザー インターフェイス (UI) を使用できます。これはUltraGrid コントロールと、単一の条件タイプを表示する UltraGrid の各行で構成されます。条件タイプは、グリッドの各行で利用可能なコントロールを使用して定義されます。この機能は、UltraGrid、UltraTab、UltraButtons、UltraFormattedLinkLabel、UltraCombo などの既存のコントロールを使用するため、新しいプロキシはありません。これにより、UltraGrid コントロールやコントロールごとに、確認ポイントを追加することができます。

*CLR4 の互換性*

2011 Volume 2 リリースでは、Infragistics CLR4 アセンブリを参照するアプリケーションと一緒に、プロキシの CLR4 互換ビルドを使用できます。

*バージョン ユーティリティ*

バージョン ユーティリティが更新されました。ドロップダウン メニューに VersionFree、CLR2、および CLR4 の各バージョンが表示されます。アセンブリの任意のビルド バージョンに切り替えることができるようになりました。(以前は、CLR2 バージョンのみが切り替え可能でした。)